version: 2.1

defaults:
  environment: &environment
    DOCKER_REGISTRY: docker.io
    DOCKER_USER: kelvintaywl

parameters:
  remote-docker-version:
    # see https://circleci.com/docs/2.0/building-docker-images/#docker-version
    type: string
    default: '20.10.18'

executors:
  cimg-base:
    docker:
      - image: cimg/base:stable
    resource_class: medium

commands:
  check-docker:
    steps:
      - run: docker version
      - run: docker info
      - run: docker compose version
      - run:
          name: check DOCKER_ env vars
          command: |
            # DOCKER_* env vars can be/are used to override some Docker config (e.g., for Docker + Remote Docker)
            # See https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
            (env | grep "DOCKER_") || true

jobs:
  explore-docker-daemon-docker:
    executor: cimg-base
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - check-docker
      - run:
          name: Spin up DB
          command: docker compose up db -d
      - run:
          name: Stop DB
          command: |
            sleep 20
            docker compose stop db

            docker compose ps -a
      - run:
          name: Start all services again
          command: docker compose up --build -d

workflows:
  explore:
    jobs:
      - explore-docker-daemon-docker
