version: 2.1

defaults:
  environment: &environment
    DOCKER_REGISTRY: docker.io
    DOCKER_USER: kelvintaywl

executors:
  ubuntu-2204:
    machine:
      image: ubuntu-2204:2022.04.1
      resource_class: medium
  cimg-base:
    docker:
      - image: cimg/base:stable
    resource_class: medium

commands:
  check-docker:
    steps:
      - run: docker version
      - run: docker info
      - run: (env | grep "DOCKER_") || true

jobs:
  explore-docker-daemon-machine:
    executor: ubuntu-2204
    steps:
      - check-docker
  explore-docker-daemon-docker:
    executor: cimg-base
    steps:
      - check-docker
  explore-docker-daemon-docker-remote:
    executor: cimg-base
    steps:
      - setup_remote_docker:
          version: 20.10.12
      - check-docker

workflows:
  explore-daemon:
    jobs:
      - explore-docker-daemon-machine:
          name: machine
      - explore-docker-daemon-docker:
          name: docker
      - explore-docker-daemon-docker-remote:
          name: docker-and-remote-docker
